name: Testing
on: [ push ]
jobs:
  build-image:
    runs-on: node:20-bullseye
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: grpc
